version: "3"
services:
  redis_sessions:
    container_name: redis_sessions
    env_file:
      - auth-service/redis.env
    image: redis
    ports:
      - "8001:8001"
      - "6379:6379"
    volumes:
      - cache:/data
  postgres_auth:
    container_name: postgres_auth
    image: postgres
    build:
      context: .
      dockerfile: ./auth-service/postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    env_file:
      - ./auth-service/postgres.env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
  auth_service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth_service
    ports:
      - "8081:8801"
      - "12201:12201"
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"


volumes:
  cache:
  postgres_auth_data:

