server:
  address: :12201
artist_storage:
  container_name: postgres_artists
  port: 5432
  database_name: artists
  database_user: postgres
  database_password: postgres
  database: postgres
  max_connections: 100
music_service:
  container_name: music_service
  port: 12201
auth_service:
  container_name: auth_service
  port: 12201